apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq-namespace
spec:
  type: NodePort
  ports:
    - port: 5672
      nodePort: 30172
      name: amqp
    - port: 15672
      nodePort: 30173
      name: management
  selector:
    app: rabbitmq

