apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: rabbitmq-workspace
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: MI_VARIABLE
      value: "pelado"
    - name: RABBITMQ_USER
      valueFrom:
        secretKeyRef:
          name: climeworks-rabbitmq-default-user
          key: username
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          name: climeworks-rabbitmq-default-user
          key: password
    ports:
    - containerPort: 80
