apiVersion: v1
kind: Pod
metadata:
  name: producer
  namespace: rabbitmq-workspace
spec:
  containers:
  - name: producer
    image: ablancog/producer-rabbitmq:0.0.15
    env:
    - name: TOTAL
      value: "100000"
    - name: CLIMEWORKS_RABBITMQ_SERVICE_HOST
      value: "10.43.222.194"
    - name: RABBITMQ_USER
      valueFrom:
        secretKeyRef:
          name: climeworks-rabbitmq-default-user
          key: username
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          name: climeworks-rabbitmq-default-user
          key: password

