apiVersion: v1
kind: Pod
metadata:
  name: producer
  namespace: rabbitmq-workspace
spec:
  containers:
  - name: producer
    image: ablancog/producer-rabbitmq:0.0.10
    env:
    - name: RABBITMQ_USER
      valueFrom:
        secretKeyRef:
          name: climeworks-rabbitmq-default-user
          key: username
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          name: climeworks-rabbitmq-default-user
          key: password

